### ISSUE TITLE
FR: locale bash script overrides time argument 

### ISSUE THREAD

**Issue by j-eid** [GoogleContainerTools/rules_distroless#110]
I was wondering if there was a reason for removing the time option and writing in `0.0` if it's being passed as an attribute and evaluated at runtime.

https://github.com/GoogleContainerTools/rules_distroless/blob/6ccc0307f618e67a9252bc6ce2112313c2c42b7f/distroless/private/locale.sh#L17

Seems like this would be fine:
```
 "$bsdtar" -cf - $@ --format=mtree --options '!gname,!uname,!sha1,!nlink,!time' "@$package_path" |  sed 's/$/ time="'$time'"/' | "$bsdtar" --gzip --options 'gzip:!timestamp' -cf "$out" -C "$tmp/" @- 
```

**Comment by thesayyn** [comment]
These are legacy workarounds we had to do implement for rules_distroless. I am not sure whats being asked here though, are asking for a feature where you can override these values or just preserve what's in the original archive?

**Comment by j-eid** [comment]
The intent was to override the values. The logic is already present in the rule and in the script. The rule implementation adds a time argument that’s passed from the time attribute in the rule. The shell script then assigns the argument to time. I was just confused why the argument wasn’t being used. The time attribute in the rule has a default value of 0.0 already as well.
