### ISSUE TITLE
Issues encountered while trying to create apt-based images 

### ISSUE THREAD

**Issue by TSkrebe** [GoogleContainerTools/rules_distroless#122]
rules_distroless: 0.3.8
bazel version: 7.4.1

I was following this documentation: https://github.com/GoogleContainerTools/rules_distroless/blob/main/docs/apt.md

1. The first thing that i noticed was the following error when running `bazel run @bullseye//:lock`
 ```
INFO: Running command line: bazel-bin/external/rules_distroless~~apt~bullseye_resolve/lock external/rules_distroless~~apt~bullseye_resolve/lock.json

Writing lockfile to test-dir/bullseye.lock.json
Error: neither WORKSPACE nor WORKSPACE.bazel file was found
```
this appears to be a red-herring since the lock file was created.

2. Then i tried to use that target to create oci_image like here https://github.com/GoogleContainerTools/rules_distroless/blob/main/examples/debian_snapshot/BUILD.bazel#L57

However, that results in an error:
```
ERROR: /xxx/src/lib/bazel/BUILD:3:10: no such target '@@rules_distroless~~apt~bullseye//:bullseye': target 'bullseye' not declared in package '' defined by /xxx/external/rules_distroless~~apt~bullseye/BUILD.bazel and referenced by '//src/lib/bazel:test-image'
```

**Comment by thesayyn** [comment]
Please use the latest version of rules_distroless. This issue is already fixed.
