### ISSUE TITLE
rules_distroless_dependencies are out of date

### ISSUE THREAD

**Issue by prestonvanloon** [GoogleContainerTools/rules_distroless#13]
PR https://github.com/GoogleContainerTools/rules_distroless/pull/12 updates MODULE.bazel but not the dependencies.

**Comment by loosebazooka** [comment]
@thesayyn ?

**Comment by thesayyn** [comment]
@prestonvanloon do you mind sending a PR for this?

**Comment by prestonvanloon** [comment]
Sure, i'll send a PR today. Thanks
