### ISSUE TITLE
Debian package management support

### ISSUE THREAD

**Issue by Sineaggi** [GoogleContainerTools/rules_distroless#15]
For example, will rules_distroless contain parts of the upstream distroless project related to downloading/extracting .deb files in order to install custom dependencies from upstream debian mirrors?

In our case, we can build off of pre-existing distroless contains (like cc, static or java_base) to add our dependencies and applications on top, so many of the rules in this repo are unnecessary. However the ability to install additional dependencies is absolutely a requirement.

**Comment by thesayyn** [comment]
We are working on this actively. See: #16

**Comment by thesayyn** [comment]
This is now supported. https://github.com/GoogleContainerTools/rules_distroless/pull/16
