### ISSUE TITLE
Publish to Bazel Central Registry is failing

### ISSUE THREAD

**Issue by mortenmj** [GoogleContainerTools/rules_distroless#20]
This PR is failing tests, apparently because the list of maintainers is empty: https://github.com/bazelbuild/bazel-central-registry/pull/1426
The maintainer list that needs to be updated is found here: https://github.com/GoogleContainerTools/rules_distroless/blob/main/.bcr/metadata.template.json#L3

**Comment by thesayyn** [comment]
This is fixed https://github.com/bazelbuild/bazel-central-registry/pull/1582
