### ISSUE TITLE
cacerts.copyright: No such file or directory

### ISSUE THREAD

**Issue by firov** [GoogleContainerTools/rules_distroless#23]
mv: rename /var/folders/19/cmgwr8k96ss7_v1yryp45cs00000gn/T/tmp.yArGxaCykT/doc/ca-certificates/copyright to bazel-out/darwin_arm64-fastbuild/bin/nebazel/deploy/cacerts.copyright: No such file or directory

--strip-components 3 removes also doc from the path.
https://github.com/GoogleContainerTools/rules_distroless/blob/8ec3bdc77c5b6d648bd936b02256017f4397b0ec/distroless/private/cacerts.sh#L12

Worked with patch:
```
diff --git a/distroless/private/cacerts.sh b/distroless/private/cacerts.sh
index 44e3f98..62bfc3c 100755
--- a/distroless/private/cacerts.sh
+++ b/distroless/private/cacerts.sh
@@ -7,7 +7,7 @@ readonly cacerts_out="$3"
 readonly copyright_out="$4"
 readonly tmp="$(mktemp -d)"

-"$bsdtar" -xf "$package_path" -C "$tmp" --strip-components 3 ./usr/share/ca-certificates ./usr/share/doc/ca-certificates/copyright
+"$bsdtar" -xf "$package_path" -C "$tmp" --strip-components 2 ./usr/share/ca-certificates ./usr/share/doc/ca-certificates/copyright

 mv "$tmp/doc/ca-certificates/copyright" "$copyright_out"
```

**Comment by firov** [comment]
Ok seems like problem with packaging with pkg_tar, if i make package with bazel it differs from .deb archive

**Comment by loosebazooka** [comment]
what a ride! please continue to report issues that you see, this project is new.
