### ISSUE TITLE
tar.zst

### ISSUE THREAD

**Issue by robertdolca** [GoogleContainerTools/rules_distroless#51]
The implementation expects `data.tar.xz` and `control.tar.xz` but some packages such as `gitweb` on `Ubuntu Jammy` have `.tar.zst` files.

```
cat ..../external/jammy_gitweb_1-2.34.1-1ubuntu1.10_amd64/BUILD.bazel

filegroup(
    name = "data",
    visibility = ["//visibility:public"],
    srcs = ["data.tar.xz"]
)

filegroup(
    name = "control",
    visibility = ["//visibility:public"],
    srcs = ["control.tar.xz"]
)
```

```
 ls ..../external/jammy_gitweb_1-2.34.1-1ubuntu1.10_amd64/
BUILD.bazel	WORKSPACE	control.tar.zst	data.tar.zst	debian-binary
```

**Comment by loosebazooka** [comment]
FYI, this project is a support ruleset for distroless and is primary funded for that purpose. If you can provide a fully tested PR with this feature, we can accept the patch, but it's unlikely that we will be handling feature requests ourselves.

**Comment by thesayyn** [comment]
This is already fixed by https://github.com/GoogleContainerTools/rules_distroless/pull/41
